### PR TITLE
Azure AKS Container Provider

### PR DESCRIPTION
**Pull request by agrare**
```
az aks get-credentials --resource-group RESOURCE_GROUP_NAME --name CLUSTER_NAME --admin
grep token ~/.kube/config
```

TODO:
- [x] DDF forms
- [x] VCR specs

Follow-ups:
* https://github.com/ManageIQ/manageiq-decorators/pull/52
* https://github.com/ManageIQ/manageiq-documentation/pull/1590

Closes https://github.com/ManageIQ/manageiq-providers-azure/issues/442

### CODE REVIEW

**Comment by agrare** [comment]
I started dynamically pulling the cluster_admin credentials from the Azure `ContainerService` API since typically these tokens have a short lifetime, but later found out that the token is good one year.

The `.kube/config` file that is built for users has no token-refresh so they take a similar approach to connecting via kubectl.

I'll leave the utility methods here to lookup cluster hostname and admin token from the API in case we want to use them over the API to dynamically look this info up for the user by cluster name.

**Comment by djberg96** [comment]
Is the azure-armrest `ContainerService` still valid? I'm having trouble finding docs on the `ContainerServices` service name. They're all dead links. It was originally added in 2017.

**Comment by agrare** [comment]
I hadn't tried it because I didn't see the `ManagedClusters` subclass which is what is needed to get the cluster endpoint and credential info but certainly not against adding it.

This is the method we need to pull the admin token (python api docs): https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerservice/azure.mgmt.containerservice.v2021_07_01.operations.managedclustersoperations?view=azure-python

**Comment by djberg96** [comment]
Ok, yep, looks like you'd need to wrap https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters for azure-armrest if you want it integrated.

**Comment by agrare** [comment]
Okay I'm going to drop the url/token lookup since they aren't currently used that way we don't add the extra gem dependency right now and we have time to get it working through azure-armrest.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Morphy branch has been created, so you can start the backport.

**Comment by Fryguy** [comment]
@agrare A conflict occurred during the backport of this pull request to `morphy`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `morphy` branch in order to resolve this.

Conflict details:

```diff
diff --cc app/models/manageiq/providers/azure/inventory.rb
index 1a9996f,b810ef6..0000000
--- a/app/models/manageiq/providers/azure/inventory.rb
+++ b/app/models/manageiq/providers/azure/inventory.rb
@@@ -9,13 -9,11 +9,21 @@@ class ManageIQ::Providers::Azure::Inven
      "CloudManager"
    end
  
++<<<<<<< HEAD
 +  def self.parser_classes_for(ems, target)
 +    case target
 +    when InventoryRefresh::TargetCollection
 +      [ManageIQ::Providers::Azure::Inventory::Parser::CloudManager,
 +       ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager]
 +    else
 +      super
++=======
+   def self.parser_classes_for(ems, _target)
+     if ems.kind_of?(ManageIQ::Providers::Azure::ContainerManager)
+       super
+     else
+       [ManageIQ::Providers::Azure::Inventory::Parser::CloudManager, ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager]
++>>>>>>> 6a89b27... Merge pull request #468 from agrare/azure_aks_container_provider
      end
    end
  end
```

**Comment by agrare** [comment]
@Fryguy there is a morphy direct PR for this one https://github.com/ManageIQ/manageiq-providers-azure/pull/468#issuecomment-907420398
#472

**Pull request merged**
