### PR TITLE
Replace stubbed authentication_status_ok? for event_catcher_spec

### PR DESCRIPTION
**Pull request by agrare**
Rather than stub ems.authentication_status_ok? and ems.supports?(:timeline) we can just create appropriate authentication records and set the capabilities

Required for: https://github.com/ManageIQ/manageiq/pull/21138

### CODE REVIEW

**Comment by Fryguy** [comment]
Backported to `lasker` in commit fdfc9374c85392019f7307c4ec5078aca6160e38.

```text
commit fdfc9374c85392019f7307c4ec5078aca6160e38
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Apr 1 17:53:09 2021 -0400

    Merge pull request #452 from agrare/dont_stub_all_ems_in_zone
    
    Replace stubbed authentication_status_ok? for event_catcher_spec
    
    (cherry picked from commit 8a06c7e4c1dc247b585a842b11e46dc7faa5e638)
```

**Comment by Fryguy** [comment]
@agrare A conflict occurred during the backport of this pull request to `kasparov`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `kasparov` branch in order to resolve this.

Conflict details:

```diff
diff --cc spec/models/manageiq/providers/azure/cloud_manager/event_catcher_spec.rb
index 086b38b,b339082..0000000
--- a/spec/models/manageiq/providers/azure/cloud_manager/event_catcher_spec.rb
+++ b/spec/models/manageiq/providers/azure/cloud_manager/event_catcher_spec.rb
@@@ -1,24 -1,25 +1,39 @@@
  describe ManageIQ::Providers::Azure::CloudManager::EventCatcher do
    context "valid ems" do
-     let(:unsupported_reason) { "Timeline events not supported for this region" }
+     let(:unsupported_reason) { "Timeline not supported for this region" }
+     let(:zone) { EvmSpecHelper.local_guid_miq_server_zone.last }
+     let!(:ems) { FactoryBot.create(:ems_azure, :with_authentication, :zone => zone, :capabilities => {"insights" => insights}) }
  
-     before do
-       @ems = FactoryBot.create(:ems_azure)
-       allow(@ems).to receive(:authentication_status_ok?).and_return(true)
-       allow(described_class).to receive(:all_ems_in_zone).and_return([@ems])
-     end
+     context "with insights enabled" do
+       let(:insights) { true }
  
++<<<<<<< HEAD
 +    it "returns a valid ems for zone if timeline events are supported" do
 +      allow(@ems).to receive(:supports_timeline?).and_return(true)
 +      expect($log).not_to receive(:info).with(/#{unsupported_reason}/)
 +      expect(described_class.all_valid_ems_in_zone).to include(@ems)
 +    end
 +
 +    it "returns an empty list for zone if timeline events are not supported" do
 +      allow(@ems).to receive(:supports_timeline?).and_return(false)
 +      allow(@ems).to receive(:unsupported_reason).and_return(unsupported_reason)
 +      expect($log).to receive(:info).with(/#{unsupported_reason}/)
 +      expect(described_class.all_valid_ems_in_zone).not_to include(@ems)
++=======
+       it "returns a valid ems for zone if timeline events are supported" do
+         expect($log).not_to receive(:info).with(/#{unsupported_reason}/)
+         expect(described_class.all_valid_ems_in_zone).to include(ems)
+       end
+     end
+ 
+     context "with insights disabled" do
+       let(:insights) { false }
+ 
+       it "returns an empty list for zone if timeline events are not supported" do
+         expect($log).to receive(:info).with(/#{unsupported_reason}/)
+         expect(described_class.all_valid_ems_in_zone).not_to include(ems)
+       end
++>>>>>>> 8a06c7e... Merge pull request #452 from agrare/dont_stub_all_ems_in_zone
      end
    end
  end
```

**Comment by agrare** [comment]
We can't backport this to kasparov directly because it uses the new-in-lasker `ExtManagementSystem#capabilities` column https://github.com/ManageIQ/manageiq-providers-azure/pull/439

I'll create a direct PR that will work with https://github.com/ManageIQ/manageiq/pull/21138

**Comment by Fryguy** [comment]
Backported to `kasparov` via https://github.com/ManageIQ/manageiq-providers-azure/pull/456

**Pull request merged**
