### PR TITLE
Service dialog for orchestration template no longer contains tenant selection

### PR DESCRIPTION
**Pull request by bzwei**
https://bugzilla.redhat.com/show_bug.cgi?id=1642594

Fixes CI build failure caused by https://github.com/ManageIQ/manageiq/pull/18202

### CODE REVIEW

**Comment by djberg96** [comment]
@bzwei Seems you broke something.

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by JPrause** [comment]
@bzwei if this can be backported, please add the hammer/yes and gaprindashvili/yes labels

**Comment by bzwei** [comment]
@miq-bot add_label hammer/yes, gaprindashvili/yes
@miq-bot assign @agrare

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit da0755a30821314c72b1a2fbdb776adef83516b1
Author: Adam Grare <agrare@redhat.com>
Date:   Mon Nov 19 11:08:40 2018 -0500

    Merge pull request #306 from bzwei/no_tenant
    
    Service dialog for orchestration template no longer contains tenant selection
    
    (cherry picked from commit c1f7dd6e3fd366788c122e1ca09be20a6d352e4f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1642594
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ddc52040b608e128a7586b95e450da34861b8cea
Author: Adam Grare <agrare@redhat.com>
Date:   Mon Nov 19 11:08:40 2018 -0500

    Merge pull request #306 from bzwei/no_tenant
    
    Service dialog for orchestration template no longer contains tenant selection
    
    (cherry picked from commit c1f7dd6e3fd366788c122e1ca09be20a6d352e4f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1651391
```

**Pull request merged**
