### PR TITLE
Azure doesn't support discovery

### PR DESCRIPTION
**Pull request by juliancheal**
Used the SupprtsFeatureMixin

Changed spec to expect supports_discovery? to return false.

### CODE REVIEW

**Comment by juliancheal** [comment]
Relies on https://github.com/ManageIQ/manageiq-ui-classic/pull/2304 being merged first

Supersedes https://github.com/ManageIQ/manageiq-providers-azure/pull/137 as I'm not sure we need to remove all the discover code in the same PR as disabling Discover.

**Comment by juliancheal** [comment]
@bronaghs the UI button change was merged. We should be good to go with this. What do you think?

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by juliancheal** [comment]
screen shot 2018-01-04 at 16 31 55

As soon as this is merged. Discover will be disabled for Cloud.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 72b90953640e66664da5f341a9495681c97d3873
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Fri Jan 5 12:45:17 2018 -0500

    Merge pull request #193 from juliancheal/disable_discovery
    
    Azure doesn't support discovery
    (cherry picked from commit dc78cae5bcdaca6c43515ae7d4c2485613682fe3)
```

**Pull request merged**
