### PR TITLE
[WIP] Remove Azure Discovery

### PR DESCRIPTION
**Pull request by juliancheal**
An Azure discovery can end up overloading the system and causing
more issues than it solves.

This feature should hopefully be reimplemented in the future after
the re-architecture.

### CODE REVIEW

**Comment by juliancheal** [comment]
This PR is related to https://github.com/ManageIQ/manageiq-providers-amazon/pull/306

**Comment by bronaghs** [comment]
specs :-)

**Comment by juliancheal** [comment]
> specs :-)

I know, I wanted Travis to earn it's keep.

Seriously though, it was so I could share with you and @djberg96 the specs I wanted to remove.

**Comment by juliancheal** [comment]
> Seriously though, it was so I could share with you and @djberg96 the specs I wanted to remove.

Oh but they don't show up in the commit as I didn't touch them. Ha `#fail`

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by juliancheal** [comment]
Links to issue https://github.com/ManageIQ/manageiq/issues/16124

**Comment by bronaghs** [comment]
@juliancheal - Does the related [UI PR ](https://github.com/ManageIQ/manageiq-ui-classic/pull/2304)have to be merged first?

**Comment by juliancheal** [comment]
@bronaghs We can merge either the Amazon one or the Azure one, but not both before the UI one. As the UI fails if there are no Cloud providers in Discovery.

**Comment by bronaghs** [comment]
OK lets make this a WIP then.

**Comment by bronaghs** [comment]
@juliancheal - bump

**Comment by juliancheal** [comment]
Closing in favour of https://github.com/ManageIQ/manageiq-providers-azure/pull/193

**Pull request closed without merging**
