### PR TITLE
[Gaprindashvili] azure graph refresh

### PR DESCRIPTION
**Pull request by Ladas**
Azure graph refresh + specs

Adding also placeholders for targeted refresh, so we can start to add it.

Partially fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1487602

### CODE REVIEW

**Comment by Ladas** [comment]
@djberg96 ready for review, the last 2 commits are extra, I've bumped the API version, so I can use the upstream VCRs. And 1 difference in graph refresh API, for g-release, that affected LB health checks

**Comment by Ladas** [comment]
@simaishi after @djberg96 reviews, you can proceed with backporting other in https://bugzilla.redhat.com/show_bug.cgi?id=1487602#c18 , locally, it doesn't throw any more conflicts

**Comment by simaishi** [comment]
@Ladas OK, will do!

**Comment by Ladas** [comment]
@simaishi we will need this backported first https://github.com/ManageIQ/manageiq-providers-azure/pull/230 , then the specs here should pass

**Comment by djberg96** [comment]
@Ladas Oh, I thought we weren't going to touch the api-versions in the config file since we merged #230

**Pull request merged**
