### PR TITLE
Handle possibility of no orchestration stacks

### PR DESCRIPTION
**Pull request by djberg96**
Fixes a potential bug in the `get_stack_templates` method.

Addresses https://github.com/ManageIQ/manageiq-providers-azure/issues/83

### CODE REVIEW

**Comment by djberg96** [comment]
@miq-bot add_label fine/yes

**Comment by djberg96** [comment]
@miq-bot add_label euwe/yes

**Comment by bzwei** [comment]
LTGM. Thanks.

**Comment by bronaghs** [comment]
@djberg96 - any chance of a spec?

**Comment by djberg96** [comment]
@bronaghs I will need some help with that. :)

**Comment by blomquisg** [comment]
@djberg96 the easiest way I can see testing this is to refactor the way that deployments are collected by adding a `get_deployments` method that simply calls `get_data_for_this_region(@tds, 'list')`.

Then, you can easily stub out that method to return an empty array, or `nil`, or whatever you need it to return to reproduce this situation.  You could probably even stub that out in the VCR-based specs, but that might result in the dreaded "Unused HTTP Calls" error.

Without that wrapper method, it looks like lots and lots of digging holes to stub out weird things.

  #justathought

**Comment by djberg96** [comment]
@blomquisg I was able to figure it out. :)

That said, I did split out a `get_deployments` method. While not strictly necessary for this PR, I included it anyway to make future testing potentially easier.

@bronaghs @bzwei Please review.

**Comment by simaishi** [comment]
@djberg96 Is there a BZ for this?  Can you please create if it doesn't exist?

**Comment by djberg96** [comment]
@simaishi https://bugzilla.redhat.com/show_bug.cgi?id=1467405

**Comment by simaishi** [comment]
@djberg96 `app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb ` is giving a conflict backporting to Euwe. Please resolve conflict and create an Euwe-specific PR (referencing this one) or suggest other PRs to backport.

```diff
++<<<<<<< HEAD
 +        old_status_message = get_resource_status_message(old_resource)
 +
 +        old_resource.properties['status_message'] = if old_status_message
 +                                                      "#{old_status_message}\n#{new_status_message}"
 +                                                    else
 +                                                      new_status_message
 +                                                    end
 +      end
 +
 +      def get_stack_template(stack, content)
 +        process_collection([stack], :orchestration_templates) { |the_stack| parse_stack_template(the_stack, content) }
++=======
+         # link stacks to templates, convert raw_template to template
+         Hash(@data_index[:orchestration_stacks]).each do |_stack_uid, stack|
+           raw_template = stack[:orchestration_template]
+           stack[:orchestration_template] = @data_index.fetch_path(:orchestration_templates, raw_template[:uid])
+         end
++>>>>>>> cb8acf4... Merge pull request #84 from djberg96/orchestration_stack_fix
        end
```

**Comment by djberg96** [comment]
@simaishi I don't know that it needs backporting to Euwe. @bzwei The logic changed between Euwe and Fine, didn't it?

**Comment by blomquisg** [comment]
@djberg96 you [added the `euwe/yes` label](https://github.com/ManageIQ/manageiq-providers-azure/pull/84#issuecomment-310950413) :)

**Comment by djberg96** [comment]
@blomquisg dang, i suck.

**Comment by djberg96** [comment]
@miq-bot add_label euwe/no

**Comment by djberg96** [comment]
@simaishi I will submit a separate PR for Euwe. Sorry about that.

**Comment by djberg96** [comment]
@miq-bot remove_label euwe/yes

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 0bea1a1b12325dfb3cbc9630158369cb72214fc8
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Tue Jun 27 16:27:31 2017 -0400

    Merge pull request #84 from djberg96/orchestration_stack_fix
    
    Handle possibility of no orchestration stacks
    (cherry picked from commit cb8acf4422799d9861f4e43a9c07d7038fbe7405)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1468703
```

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/15527

**Pull request merged**
