### PR TITLE
Disable/Enable support for specific regions.

### PR DESCRIPTION
**Pull request by bronaghs**
- Disable/Enable support for specific Azure regions.
- New government regions added (Texas, Arizona).

This PR depends on the following PR being merged into the manageiq repo first: https://github.com/ManageIQ/manageiq/pull/13156

https://bugzilla.redhat.com/show_bug.cgi?id=1403366

### CODE REVIEW

**Comment by djberg96** [comment]
LGTM. Seems there's an unrelated bower error.

**Comment by bronaghs** [comment]
@miq-bot add_label darga/yes, euwe/yes

**Comment by chessbyte** [comment]
Euwe BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1404827
https://bugzilla.redhat.com/show_bug.cgi?id=1404871

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log -1
commit d7381914e78cbfd3ad2c91ac0688e2a50b40cde5
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Wed Dec 14 12:58:58 2016 -0500

    Merge pull request #19 from bronaghs/master
    
    Disable/Enable support for specific regions.
    (cherry picked from commit 0369dabeccf0d4c4d7ca74e2f4113d71daf00040)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1404827
    https://bugzilla.redhat.com/show_bug.cgi?id=1404871
```

**Comment by chessbyte** [comment]
Darga BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1404829
https://bugzilla.redhat.com/show_bug.cgi?id=1405207

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git log -1
commit bcb02c4967f436683590ccf5f4a079efc340f127
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Wed Dec 14 12:58:58 2016 -0500

    Merge pull request #19 from bronaghs/master
    
    Disable/Enable support for specific regions.
    (cherry picked from commit 0369dabeccf0d4c4d7ca74e2f4113d71daf00040)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1404829
    https://bugzilla.redhat.com/show_bug.cgi?id=1405207
```

**Pull request merged**
