### PR TITLE
run provider generator to sync changes from core

### PR DESCRIPTION
**Pull request by durandom**
ran the generator again with

```bash
bundle exec rails g provider <name> --path ../
```

these are the changes.

### CODE REVIEW

**Comment by djberg96** [comment]
@durandom Can you tell me at a high level what these changes are for exactly?

**Comment by durandom** [comment]
* refactoring running specs to exclude `spec/manageiq` in `.rspec`
* streamline README with other repos
* include possible shared specs local to this repo

**Comment by djberg96** [comment]
@durandom any reason not to just remove azure.rake?

**Comment by durandom** [comment]
I'd keep it for consistencies sake and to act as a boilerplate for future tasks...

**Pull request merged**
