### PR TITLE
Removes what I think is an unnecessary public rake task file

### PR DESCRIPTION
**Pull request by d-m-u**
This code shouldn't be needed because the private version does exactly this and, well, is private.

### CODE REVIEW

**Comment by bronaghs** [comment]
I am actually not sure if this file is needed or not. I will assign to @Fryguy.

**Comment by d-m-u** [comment]
@miq-bot add_label technicaldebt, cleanup

**Comment by d-m-u** [comment]
@miq-bot add-label technical debt

**Comment by d-m-u** [comment]
@agrare thanks for doing the others, may I give you this too, please?

**Comment by bronaghs** [comment]
@d-m-u - Do you know why we have a public and a private version?

**Comment by d-m-u** [comment]
I do not, but I do know that Jason told me to remove this one.

**Pull request merged**
