### PR TITLE
Add support for regions in Germany

### PR DESCRIPTION
**Pull request by djberg96**
This PR adds support for regions in Germany.

~~~This is a WIP for now until I can get some credentials that actually have access to these regions. There's also the issue of listing regions that may not be available for the given subscription, though the validate button should reveal any issues.~~~

Update: Support for regions in China will be added later in a separate PR.

### CODE REVIEW

**Comment by djberg96** [comment]
Confirmed that validation will fail if the subscription does not support the region. The "Add" button is greyed out in the UI until validation is successful.

**Comment by djberg96** [comment]
@miq-bot remove_label wip

**Comment by djberg96** [comment]
I managed to get a service principal setup for Germany and tested it with azure-armrest successfully, so I'm removing the WIP label.

**Comment by bronaghs** [comment]
If you only tested with Germany, the China regions should be added later.

**Comment by bronaghs** [comment]
hey @djberg96 - What is the status of this PR?
I saw an email notification stating that the regions support has since changed on the Azure side, would be worthwhile checking to see if we need to update our supported list.

**Comment by djberg96** [comment]
@bronaghs I was hoping to get some credentials for a China region before messing with this PR, but that didn't happen. I'll double check the current list and see if there are any other regions to add.

**Comment by djberg96** [comment]
@bronaghs Ok, I've removed references to China for now.

**Comment by djberg96** [comment]
@bronaghs Updated.

**Comment by bronaghs** [comment]
@djberg96 - Any reason why support for Germany cannot be backported to fine?

**Comment by djberg96** [comment]
@bronaghs As long as there's a BZ, should be ok. :)

**Pull request merged**
