### PR TITLE
Remove MariaDB

### PR DESCRIPTION
**Pull request by klim-iv**
Due to error on _Azure_, needs to remove **MariaDB** from this provider:
```
The operation is not permitted for namespace 'Microsoft.DBforMariaDB'. List of permitted provider namespaces is:
'Auth0.Cloud,Citrix.Services,Hive.Streaming,Lombiq.DotNest,Microsoft.AAD,microsoft.aadiam,Microsoft.ADHybridHealthService,Microsoft.Advisor,Microsoft.AlertsManagement,Microsoft.AnalysisServices,Microsoft.ApiManagement,Microsoft.AppAssessment,Microsoft.AppConfiguration,Microsoft.Authorization,Microsoft.Automation,Microsoft.AVS,Microsoft.AzureActiveDirectory,Microsoft.AzureStack,Microsoft.AzureStackHCI,Microsoft.BareMetalInfrastructure,Microsoft.Batch,Microsoft.Billing,Microsoft.Blueprint,Microsoft.BotService,Microsoft.Cache,Microsoft.Capacity,Microsoft.Cdn,Microsoft.CertificateRegistration,Microsoft.ChangeAnalysis,Microsoft.ClassicCompute,Microsoft.ClassicNetwork,Microsoft.ClassicStorage,Microsoft.CognitiveServices,Microsoft.Communication,Microsoft.Compute,Microsoft.Consumption,Microsoft.ContainerInstance,Microsoft.ContainerRegistry,Microsoft.ContainerService,Microsoft.CostManagement,Microsoft.CostManagementExports,Microsoft.CustomProviders,Microsoft.DataBox,Microsoft.DataBoxEdge,Microsoft.Databricks,Microsoft.DataCatalog,Microsoft.DataFactory,Microsoft.DataLakeAnalytics,Microsoft.DataLakeStore,Microsoft.DataMigration,Microsoft.DataPlatform,Microsoft.DBforMySQL,Microsoft.DBforPostgreSQL,Microsoft.DeploymentManager,Microsoft.DesktopVirtualization,Microsoft.DevHub,Microsoft.Devices,Microsoft.DevTestLab,Microsoft.DocumentDB,Microsoft.DomainRegistration,Microsoft.Education,Microsoft.EventGrid,Microsoft.EventHub,Microsoft.Features,Microsoft.Genomics,Microsoft.GuestConfiguration,Microsoft.HanaOnAzure,Microsoft.HardwareSecurityModules,Microsoft.HDInsight,Microsoft.HpcWorkbench,Microsoft.HybridCompute,Microsoft.ImportExport,microsoft.insights,Microsoft.IoTCentral,Microsoft.IoTSpaces,Microsoft.KeyVault,Microsoft.Kusto,Microsoft.LabServices,Microsoft.Logic,Microsoft.M365,Microsoft.MachineLearning,Microsoft.MachineLearningServices,Microsoft.Maintenance,Microsoft.ManagedIdentity,Microsoft.ManagedServices,Microsoft.ManagementPartner,Microsoft.Maps,Microsoft.Marketplace,Microsoft.MarketplaceOrdering,Microsoft.Media,Microsoft.Migrate,Microsoft.ModSimWorkbench,Microsoft.NetApp,Microsoft.Network,Microsoft.NetworkCloud,Microsoft.Notebooks,Microsoft.NotificationHubs,Microsoft.OffAzure,Microsoft.OperationalInsights,Microsoft.OperationsManagement,Microsoft.Peering,Microsoft.PolicyInsights,Microsoft.Portal,Microsoft.PowerBI,Microsoft.PowerBIDedicated,Microsoft.PowerPlatform,Microsoft.RecoveryServices,Microsoft.Relay,Microsoft.ResourceHealth,Microsoft.Resources,Microsoft.ResourcesTopology,Microsoft.ResourcesTopology.PPE,Microsoft.Scheduler,Microsoft.Search,Microsoft.Security,Microsoft.SecurityGraph,Microsoft.SecurityInsights,Microsoft.SerialConsole,Microsoft.SerialConsole.PPE,Microsoft.ServiceBus,Microsoft.ServiceFabric,Microsoft.SignalRService,Microsoft.SiteRecovery,Microsoft.Solutions,Microsoft.Sql,Microsoft.SqlVirtualMachine,Microsoft.Storage,Microsoft.StorageSync,Microsoft.StorSimple,Microsoft.StreamAnalytics,Microsoft.Subscription,microsoft.support,Microsoft.Teams,Microsoft.TimeSeriesInsights,microsoft.visualstudio,Microsoft.VMwareCloudSimple,Microsoft.Web,Microsoft.WindowsIoT,Microsoft.WorkloadMonitor,Myget.PackageManagement,RavenHq.Db,Sendgrid.Email,SolarWinds.Observability,U2uconsult.TheIdentityHub,Wandisco.Fusion'
```
Linked with: https://github.com/ManageIQ/azure-armrest/pull/424

### CODE REVIEW

**Comment by Fryguy** [comment]
@klim-iv Do you have any information about this removal from Azure's side in official docs somewhere?  My only real concern is if there are existing Maria DB instances that Azure still allows to run, we need a way to continue to identify them.

**Comment by klim-iv** [comment]
> @klim-iv Do you have any information about this removal from Azure's side in official docs somewhere? Asking because when I did a quick search MariaDB is still all over their site, including the pricing page.
> My only real concern is if there are existing Maria DB instances that Azure still allows to run, we need a way to continue to identify them

Hello, @Fryguy!
I am sorry, I have no such info, but get error in **azure-armrest**  this error (see [comment](https://github.com/ManageIQ/manageiq-providers-azure/pull/530#issue-1558109749)):

```
The operation is not permitted for namespace 'Microsoft.DBforMariaDB'. List of permitted provider namespaces is: ...
```

**Comment by klim-iv** [comment]
Hello, have any decision about this pachset?

**Comment by agrare** [comment]
Hey @klim-iv sorry I haven't had time to test this sooner.

I haven't seen any indication in the API docs that `Microsoft.DBforMariaDB` has gone away: https://learn.microsoft.com/en-us/rest/api/mariadb/databases

I just added our azure environment and I see a successful API call to that API group:
```
[----] W, [2023-02-13T08:26:11.824777 #84625:94e8]  WARN -- azure: RestClient.get "https://management.azure.com/subscriptions/0e0a4287-8719-4849-bb0b-5242e4507709/providers/Microsoft.DBforMariaDB/servers?api-version=2018-06-01", "Accept"=>"application/json", "Authorization"=>"Bearer [FILTERED] ", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.1.0 (linux-gnu   x86_64) ruby/3.0.4p208"
[----] W, [2023-02-13T08:26:11.936087 #84625:94e8]  WARN -- azure: # => 200 OK | application/json 12 bytes, 0.11s
```

I'm guessing this is related to permissions on your account rather than the API being deleted without prior deprecation notice.

**Pull request closed without merging**
