### PR TITLE
Bump azure-armrest gem to 0.9.5

### PR DESCRIPTION
**Pull request by jerryk55**
Pick up the changes to the azure-armrest gem that increase the speed of
Managed Disk Smartstate Analysis

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1508154

@djberg96 please review.

Needs backporting to Fine and Gaprindashvili

### CODE REVIEW

**Comment by jerryk55** [comment]
@miq-bot add_label fine/yes

**Comment by djberg96** [comment]
👍

**Comment by jerryk55** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by bronaghs** [comment]
@djberg96 - any risk to backporting to fine and gaprandishvili?

**Comment by djberg96** [comment]
@bronaghs No issues, and could potentially help, as 0.9.4 was bug fixes.

**Comment by simaishi** [comment]
Note: Backported to Fine branch now, but 0.9.5 is already being used in Fine branch as https://github.com/ManageIQ/manageiq-smartstate/pull/50 was backported to Fine in January.

Fine backport details:

```
$ git log -1
commit 9261625d36cda50da245c453922a7cfd0003e4f1
Author: Daniel Berger <djberg96@gmail.com>
Date:   Mon Jan 29 14:33:49 2018 -0700

    Merge pull request #204 from jerryk55/bump_azure-armtest_to_0.9.5
    
    Bump azure-armrest gem to 0.9.5
    (cherry picked from commit 49151243bb62fdff0793fb6e0c45cc60330c3d90)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1541163
```

**Pull request merged**
