### PR TITLE
Update api-version string settings

### PR DESCRIPTION
**Pull request by djberg96**
This updates the api-version strings to the latest version for each service. We typically want to have each release on the latest api-version string, not only because new information may have been added or changed, but also because Azure eventually drops support for older api-versions.

A breakdown of the individual changes are as follows. Note that I am only looking at the output for individual records.

* AvailabilitySetService: No noticeable difference.
* NetworkSecurityGroupService: Now supports arrays of port ranges, prefixes, etc, in certain regions.
* IpAddressService: Sku information added.
* LoadBalancerService: Sku information added.
* Storage::ImageService: No noticeable difference.
* Network::NetworkInterfaceService: Adds a `virtualNetworkTapProvisioningState` property.
* ResourceService: No noticeable difference.
* ResourceGroupService: No noticeable difference.
* StorageAccountService: Adds the `networkAcls` property.
* TemplateDeploymentService: The ID elements of `outputResources` now contains a full ID instead of an abbreviated ID.
* VirtualMachineService: No noticeable difference.
* VirtualNetworkService: Adds the `enableDdosProtection` and `enableVmProtection` boolean properties.

Most of these changes will have no bearing on our current code. The change to NetworkSecurityGroupService was already handled by https://github.com/ManageIQ/manageiq-providers-azure/pull/180.

The only change that *might* be of concern is the TemplateDeploymentService change, but I don't see `outputResources` being referenced directly anywhere.

### CODE REVIEW

**Comment by djberg96** [comment]
@bzwei Can you confirm that the change to `outputResources` in the `TemplateDeploymentService` won't affect us?

**Comment by bronaghs** [comment]
Great. I will wait for @bzwei 's approval on the template piece before merging

**Comment by djberg96** [comment]
@bronaghs I took the thumbs-up from @bzwei to mean that we were clear. :)

**Comment by bronaghs** [comment]
Ah, you would be correct. 
Specs are failing, from a brief look, it seems that you need to regenerate cassettes.

**Pull request merged**
