### PR TITLE
 Move OrchestrationTemplateAzure to manageiq-providers-azure

### PR DESCRIPTION
**Pull request by bzwei**
Prepare to move OrchestrationTemplate to each provider
  
   This is a step before the migration.

    https://bugzilla.redhat.com/show_bug.cgi?id=1417021

### CODE REVIEW

**Comment by bzwei** [comment]
@miq-bot add_label refactoring
@miq-bot assign @djberg96 @bronaghs

**Comment by bzwei** [comment]
@miq-bot assign @bronaghs

**Comment by bronaghs** [comment]
@bzwei - I see the PR to change the schema, guess there will be one for the manageiq repo to delete this code from there.

**Comment by bzwei** [comment]
Yes, absolutely. Because we have multiple repos we have to do it with more steps.

**Pull request merged**
