### PR TITLE
[Changelog] Rollup of Ivanchuk releases

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
@JPrause This looks odd, now we've lost `hammer-10` section. Since`hammer-10` is already released and `ivanchuk-1` is not, `hammer-10` changelog should stay in `master` branch.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 0ee8845cafe86e0cb30892d61155b9c6556ea39d
Author: Adam Grare <agrare@redhat.com>
Date:   Fri Sep 6 14:56:46 2019 -0400

    Merge pull request #349 from JPrause/ivanchukGA_cl
    
    [Changelog] Rollup of Ivanchuk releases
    
    (cherry picked from commit 8ce95c67f66d586bead1c07a3981ac23c152d4e6)
```

**Comment by JPrause** [comment]
> @JPrause This looks odd, now we've lost `hammer-10` section. Since`hammer-10` is already released and `ivanchuk-1` is not, `hammer-10` changelog should stay in `master` branch.

@simaishi yeah I understand. I got a little "clean-up" happy. But I understand what you're saying and will keep that in mind for future edits.

**Pull request merged**
