### PR TITLE
Ignore case when gathering data for region

### PR DESCRIPTION
**Pull request by djberg96**
This PR addresses what I consider a bug in the Azure REST API. The location for any given Azure resource is *supposed* to be lowercase, but in at least one case it's not. This PR modifies our data gathering method to ignore case where possible.

Specifically, virtual machines within any India region are mixed case, and that causes our refresh parser to miss them. Note that other resources within an India region have the location set as expected.

~~~WIP for now as I would like to add some specs.~~~

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1473619

### CODE REVIEW

**Comment by djberg96** [comment]
I actually think I'll make the change in the azure-armrest gem instead:

https://github.com/ManageIQ/azure-armrest/pull/291

**Comment by djberg96** [comment]
Upon further review, we'll need to fix it in the provider after all because we're using `select` after a list_all instead of the filter because not all resources have a `location` attribute.

**Comment by djberg96** [comment]
@miq-bot add_label fine/yes

**Comment by djberg96** [comment]
@miq-bot add_label euwe/yes

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit f849e04357782e838f3f6b56e9c03a6194158c2c
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Mon Aug 7 16:28:41 2017 -0400

    Merge pull request #99 from djberg96/location_case
    
    Ignore case when gathering data for region
    (cherry picked from commit 6baf4610196e59054ccbd861614cbdab9146dd9f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1479437
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 1a884a6a2e358ba1bd7e2493ac9acf99a9052ec8
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Mon Aug 7 16:28:41 2017 -0400

    Merge pull request #99 from djberg96/location_case
    
    Ignore case when gathering data for region
    (cherry picked from commit 6baf4610196e59054ccbd861614cbdab9146dd9f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1481862
```

**Pull request merged**
