### PR TITLE
[REFACTOR] Set instance location to region location instead of using uid value

### PR DESCRIPTION
**Pull request by djberg96**
I'm not sure why we're setting the `location` for a vm instance to the `uid` value. This PR sets it to the location (region) value, e.g. "eastus".

### CODE REVIEW

**Comment by jerryk55** [comment]
miq-bot add_label fine/yes

**Comment by djberg96** [comment]
@jerryk55 Another possible solution is to access ems.provider region if you have access to it.

**Comment by jerryk55** [comment]
@djberg96 that is true but that will require modifying an existing PRs rather than just back-porting this PR.  Your mileage may vary but I would think this is the preferred route.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit b75fb9b42252ac693710b7314b7e0d99462943fb
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Fri Apr 28 16:02:04 2017 -0400

    Merge pull request #62 from djberg96/instance_location
    
    [REFACTOR] Set instance location to region location instead of using uid value
    (cherry picked from commit 04e380b10436073bbc291dc75124bd5e031e5f0d)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1488967
```

**Pull request merged**
