### PR TITLE
Don't use #{} inside gettext strings

### PR DESCRIPTION
**Pull request by mzazrivec**
`#{}` inside a gettext string wont work, use `%{}` instead.

### CODE REVIEW

**Comment by djberg96** [comment]
@mzazrivec Is this something you can add a spec for?

**Comment by mzazrivec** [comment]
@djberg96 Probably yes, although this needs to be done as a shared spec for all repos, so the actual spec would have to land in core (i.e. it will be a different PR from this).

**Comment by djberg96** [comment]
@mzazrivec Alright, once you create the shared spec (and it passes), then I'll merge.

**Comment by mzazrivec** [comment]
> @mzazrivec Alright, once you create the shared spec (and it passes), then I'll merge.

To actually test what you're asking here, you need to extract the strings from the sources and parse the resulting catalog for `#{}`. So you're not going to see any passing spec here really, not unless somebody creates a PR with updated catalogs, which happens very rarely (the only person doing that is me).

**Comment by mzazrivec** [comment]
> @mzazrivec Alright, once you create the shared spec (and it passes), then I'll merge.

Also, by definition of things, I cannot create a passing spec before this PR is merged.

**Comment by djberg96** [comment]
@mzazrivec I see you added some changes. When it's ready to go let me know and I'll merge.

**Comment by mzazrivec** [comment]
@djberg96 Yes, this one is good to go.

**Comment by mzazrivec** [comment]
By the way, the spec we were discussing here got merged here: https://github.com/ManageIQ/manageiq/pull/17684 (which is why I had to include a new gettext catalog into this PR for it to pass CI).

**Comment by djberg96** [comment]
Great, thanks!

**Comment by djberg96** [comment]
@mzazrivec Note that this won't be backported without a BZ. If you need it backported, please create one. For now I've set the backport labels to "No".

**Comment by mzazrivec** [comment]
Nah, I don't think a backport is needed here.

**Pull request merged**
