### PR TITLE
Move from MIQ repo to provider repo.

### PR DESCRIPTION
**Pull request by djberg96**
Just moving this over to our provider-specific repo.

@durandom Is there anything else that needs to happen for this to be picked up?

### CODE REVIEW

**Comment by durandom** [comment]
@djberg96 oh, I have _zero_ knowledge about those product files :( 
I'm not sure what picks those files up.
Is that automates domain?

**Comment by gmcculloug** [comment]
These files get seeded in the database from [app/models/miq_dialog.rb] (https://github.com/ManageIQ/manageiq/blob/28ea1414befb2aee4152dba397d04250b93b6bfd/app/models/miq_dialog.rb#L16).

Have we updated any seeding methods to deal with pluggable providers?  Is there a pattern for this yet?

**Comment by durandom** [comment]
@gmcculloug 
> Have we updated any seeding methods to deal with pluggable providers? Is there a pattern for this yet?

Seeding as in [EvmDatabase.seed](https://github.com/durandom/manageiq/blob/17871535a1ff95f69efab3121da89ac56e544078/lib/evm_database.rb#L55) just works ™️  because of descendent_loader.

For loading files, we havent moved anything yet 😢 
But we have [Vmdb::Plugins](https://github.com/ManageIQ/manageiq/blob/master/lib/vmdb/plugins.rb) that is used in @bdunne https://github.com/ManageIQ/manageiq/pull/11083

@bdunne am I right, that once https://github.com/ManageIQ/manageiq/pull/11083 is merged this could act as a model for seeding dialogs as well?

**Comment by bdunne** [comment]
@durandom That's a different seed for the dialogs.  Check out [MiqDialog.seed](https://github.com/ManageIQ/manageiq/blob/master/app/models/miq_dialog.rb#L21).

**Comment by durandom** [comment]
> could act as a model for seeding

Oh, I meant to act as a role model, like a pattern for doing this kind of file seeding.
So once https://github.com/ManageIQ/manageiq/pull/11083 is merged we should look into how the dialog files are seeded

**Comment by durandom** [comment]
Added [WIP] as we dont have a way of seeding dialogs yet

**Comment by djberg96** [comment]
@durandom ManageIQ/manageiq#11083 was merged. Should we revisit?

**Comment by bdunne** [comment]
@djberg96 I think the dialog files should live under `content/dialogs`.  Still, we need the Dialog seeder to know about plugins first.

**Comment by djberg96** [comment]
@durandom Done.

https://github.com/ManageIQ/manageiq/pull/14655

**Pull request merged**
