### PR TITLE
changes from provider generator

### PR DESCRIPTION
**Pull request by durandom**
same changes as here https://github.com/ManageIQ/manageiq-providers-amazon/pull/97

* leverage ManageIQ::Environment for setup
* dev dependencies in gemspec
* rubocop definition from managiq/guides

### CODE REVIEW

**Comment by durandom** [comment]
@bronaghs @djberg96 can you have a look why the vcr specs are failing here?
This PR  is needed to make master green again

**Comment by durandom** [comment]
So, I had to re-generate the cassettes due to an update of the armrest gem.

It's green now.

@bronaghs dare to merge?

**Comment by bronaghs** [comment]
@djberg96 can you review please.

**Comment by djberg96** [comment]
LGTM.

**Pull request merged**
