### PR TITLE
Added azure_tenant_id to API_ALLOWED_ATTRIBUTES

### PR DESCRIPTION
**Pull request by juliancheal**
This is a follow on PR from https://github.com/ManageIQ/manageiq/pull/16802/
and https://github.com/ManageIQ/manageiq-api/pull/279

### CODE REVIEW

**Comment by juliancheal** [comment]
@jntullo With your two PRs we'd add something like this?

**Comment by juliancheal** [comment]
@miq-bot add_label enhancement

**Comment by jntullo** [comment]
@juliancheal yup, exactly! LGTM!

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by juliancheal** [comment]
@jntullo @djberg96 updated to be a method and not a constant.

**Comment by bronaghs** [comment]
@juliancheal - Can the WIP label be removed now?

**Comment by juliancheal** [comment]
@miq-bot remove_label wip

**Pull request merged**
