### PR TITLE
Update armrest version to 0.7.0

### PR DESCRIPTION
**Pull request by djberg96**
This bumps the azure-armrest version up to 0.7.0. 

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1434988

The major version changes shouldn't be scary. The change from 0.5.x to 0.6.x was caused by an incompatible change to Role classes that we don't use internally. The change from 0.6.x to 0.7.x is the backwards incompatible, but necessary, change for getting templates.

Other than a redundant `.to_s` call, there should be no issues on the ManageIQ side.

### CODE REVIEW

**Comment by djberg96** [comment]
@miq-bot add_label euwe/yes

**Comment by djberg96** [comment]
@miq-bot add_label darga/yes

**Comment by djberg96** [comment]
I think this will fail until https://github.com/ManageIQ/manageiq-gems-pending/pull/100 is merged.

**Comment by djberg96** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 052a5f6f9b9dd7eb17bac1097a016776f3778e21
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Fri Mar 31 16:34:09 2017 -0400

    Merge pull request #42 from djberg96/armrest_version
    
    Update armrest version to 0.7.0
    (cherry picked from commit c318b5deb87c8f114921bbdd8d84c2abcfb19dd5)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1438092
```

**Comment by simaishi** [comment]
@djberg96 Can you please create an Euwe PR for this PR and https://github.com/ManageIQ/manageiq-gems-pending/pull/100/files combined?

**Comment by djberg96** [comment]
@simaishi Ok, please see https://github.com/ManageIQ/manageiq/pull/14799

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/14799

**Pull request merged**
