### PR TITLE
Update VCR cassettes

### PR DESCRIPTION
**Pull request by djberg96**
A recent api-version update from Azure broke our specs. This updates the cassettes with the current api-version string.

### CODE REVIEW

**Comment by simaishi** [comment]
Should this be `gaprindashvili/yes` ?

**Comment by djberg96** [comment]
@simaishi let me test to make sure it will work. Otherwise I'll create a separate PR.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 053c8db0c423dd69546e80f1fde7709b91ecc836
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 1 19:54:09 2017 -0500

    Merge pull request #179 from djberg96/vcr_cassettes
    
    Update VCR cassettes
    (cherry picked from commit 22caf2049a4ae31871cb0841f26f94a8e8d2aad0)
```

**Comment by simaishi** [comment]
@djberg96 What about `fine` branch?

**Comment by djberg96** [comment]
@simaishi I think I'll have to regenerate them separately for Fine because of some other changes.

**Comment by djberg96** [comment]
@simaishi Upon further review, I think the issue is just my local env. Go ahead and backport to Fine. If it breaks we can roll it back.

**Comment by simaishi** [comment]
@djberg96 6 out of 8 files are conflicting. Should I just take all files from the PR, ignoring the conflicts?

**Comment by djberg96** [comment]
@simaishi Yes, go ahead.

**Comment by simaishi** [comment]
Thanks Dan.

Fine backport details:

```
$ git log -1
commit f7740e01b62c2875fd9278432d33423ae0017b7e
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 1 19:54:09 2017 -0500

    Merge pull request #179 from djberg96/vcr_cassettes
    
    Update VCR cassettes
```

**Comment by simaishi** [comment]
@djberg96 Travis is still failing for Fine branch after backporting this PR. Would you mind taking a look?

https://travis-ci.org/ManageIQ/manageiq-providers-azure/builds/312458029

**Comment by djberg96** [comment]
Somehow it's picking up a different api-version for the virtual machine service. Not sure what's happening yet.

**Comment by djberg96** [comment]
@simaishi Sorry, that will need to be rolled back. Please see https://github.com/ManageIQ/manageiq-providers-azure/pull/184.

**Comment by simaishi** [comment]
@djberg96 To clarify... when you say "need to be rolled back",  I'd actually need to revert the backport of this PR in Fine branch, before taking https://github.com/ManageIQ/manageiq-providers-azure/pull/184?

**Comment by djberg96** [comment]
@simaishi I guess it doesn't technically need to be rolled back. If you merge 184, it should be fine then.

**Pull request merged**
