### PR TITLE
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

### PR DESCRIPTION
**Pull request by bdunne**
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

### CODE REVIEW

**Comment by djberg96** [comment]
We can switch to bionic. We have the technology.

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 291ea8466b4193fa3d9a83316e439750b7796078.

```text
commit 291ea8466b4193fa3d9a83316e439750b7796078
Author: Adam Grare <adam@grare.com>
Date:   Thu Sep 30 18:14:38 2021 -0400

    Merge pull request #476 from bdunne/update_travis_dist
    
    Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
    
    (cherry picked from commit 94d32303aa92ce81889b01e0ae63051c0583a7f6)
```

**Comment by Fryguy** [comment]
Backported to `lasker` in commit 1351446f933deb2f6af4b8bb643c15693f0fc303.

```text
commit 1351446f933deb2f6af4b8bb643c15693f0fc303
Author: Adam Grare <adam@grare.com>
Date:   Thu Sep 30 18:14:38 2021 -0400

    Merge pull request #476 from bdunne/update_travis_dist
    
    Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
    
    (cherry picked from commit 94d32303aa92ce81889b01e0ae63051c0583a7f6)
```

**Comment by Fryguy** [comment]
Backported to `kasparov` in commit baaadd09be24b4c883782f85ad1c573e710e82f4.

```text
commit baaadd09be24b4c883782f85ad1c573e710e82f4
Author: Adam Grare <adam@grare.com>
Date:   Thu Sep 30 18:14:38 2021 -0400

    Merge pull request #476 from bdunne/update_travis_dist
    
    Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
    
    (cherry picked from commit 94d32303aa92ce81889b01e0ae63051c0583a7f6)
```

**Pull request merged**
