### PR TITLE
[GAPRINDASHVILI] labels and tags mapping support

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
This is a G-backport of https://github.com/ManageIQ/manageiq-providers-azure/pull/231 and https://github.com/ManageIQ/manageiq-providers-azure/pull/229 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1568807

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
@simaishi @Ladas @bronaghs please review

**Comment by simaishi** [comment]
@AlexanderZagaynov Please add details (BZ link, 'master' PR link, etc.)

**Comment by simaishi** [comment]
@AlexanderZagaynov same question here (as https://github.com/ManageIQ/manageiq/pull/17321). If this is a cherry-pick from 'master' PRs, this PR isn't needed...

**Comment by AlexanderZagaynov** [comment]
@simaishi yes, this is cherry-pick from both PRs

**Comment by AlexanderZagaynov** [comment]
closing in favour of direct cherry-picking by @simaishi

**Pull request closed without merging**
