### PR TITLE
Ensure managers change zone and provider region with CloudManager

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/manageiq/pull/14741

Ensure managers change zone and provider region with CloudManager

Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1440327

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot add_label euwe/yes, fine/yes, bug

**Comment by Ladas** [comment]
@miq-bot assign @bronaghs

**Comment by djberg96** [comment]
👏

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 1d98337e7042169402804fcf2c206f17975979c3
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Wed Apr 12 11:16:05 2017 -0400

    Merge pull request #47 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with CloudManager
    (cherry picked from commit 76299c0ddc050e5ea40dcaf91b278ac105811260)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441753
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 5a8d16a9c12f083e90392d1980f3e66ef3d3c86a
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Wed Apr 12 11:16:05 2017 -0400

    Merge pull request #47 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with CloudManager
    (cherry picked from commit 76299c0ddc050e5ea40dcaf91b278ac105811260)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441754
```

**Pull request merged**
