### PR TITLE
Move orchestration template fixture to this repo

### PR DESCRIPTION
**Pull request by bzwei**
As title. Similar work has been done to other providers. It is part of the work described in https://github.com/ManageIQ/manageiq/issues/15985

### CODE REVIEW

**Comment by bzwei** [comment]
@miq-bot add_label test
@miq-bot add_label refactoring
@miq-bot assign @bronaghs

**Comment by djberg96** [comment]
Looks ok to me.

**Comment by bronaghs** [comment]
I see you have made this specific to JSON, are you paving the way for YAML support too?

**Comment by bzwei** [comment]
I am not aware of any Azure template format in YAML. We cannot do an actual relocation from one repo to another. I introduce the new name `orchestration_template_azure_in_json` to distinguish from the old name that still exists in the manageiq repo.

**Pull request merged**
