### PR TITLE
move settings from core repo

### PR DESCRIPTION
**Pull request by durandom**
just transferred the settings from the core repo

### CODE REVIEW

**Comment by djberg96** [comment]
Looks ok to me. I do wonder if anything gems-pending will need an update, though.

**Comment by durandom** [comment]
>  I do wonder if anything gems-pending will need an update

What do you mean by that?

**Comment by djberg96** [comment]
@durandom Will anything in gems-pending be negatively affected by this move?

**Comment by durandom** [comment]
@djberg96 oh, I dont know 😄 What has gems-pending to do with the settings.yml ?

**Comment by djberg96** [comment]
This was the only reference I could find:

https://github.com/ManageIQ/manageiq-gems-pending/blob/0441a53b546edbd8ee2c08185f533d99201f3e15/lib/gems/pending/util/mount/miq_generic_mount_session.rb#L83

Not going to worry about it I suppose.

👍

**Comment by djberg96** [comment]
@bronaghs Look alright?

**Comment by durandom** [comment]
> This was the only reference I could find:

cool find 😄 way to refactor this...

**Pull request merged**
