### PR TITLE
Bump azure-armrest dependency to 0.8.2

### PR DESCRIPTION
**Pull request by djberg96**
The 0.8.2 release contains some important bug fixes and features. We should upgrade.

https://github.com/ManageIQ/azure-armrest/blob/master/CHANGES#L1-L16

### CODE REVIEW

**Comment by djberg96** [comment]
@miq-bot add_label fine/yes

**Comment by djberg96** [comment]
@miq-bot add_label euwe/yes

**Comment by simaishi** [comment]
Marking as blocker (for Fine branch) as https://bugzilla.redhat.com/show_bug.cgi?id=1475540 needs this change.

@djberg96 I don't see any BZs associated for Euwe branch backport. Does this fix any BZ for Euwe branch?

**Comment by djberg96** [comment]
@simaishi Not explicitly, but I like to keep the branches in sync if possible.

**Comment by simaishi** [comment]
@djberg96 Changes going to non-master branch requires a BZ, marking as `bugzilla needed`

**Comment by simaishi** [comment]
Also a note: Fine branch is using `0.7.4` and Euwe is using `0.7.3`. So this update is going to pick up all changes made after those versions in each branch, not just 0.8.1 -> 0.8.2 changes. That's one more reason a BZ is needed for, as we need to identify what changed and what need to be tested.

**Comment by djberg96** [comment]
@simaishi I'll just remove the euwe label for now. Please proceed with the fine backport.

**Comment by djberg96** [comment]
@miq-bot remove_label euwe/yes

**Comment by simaishi** [comment]
Fine backport (to manageiq-gems-pending repo) details:

```
$ git log -1
commit db8dadd367cd34e7d7acc1d95f5637e6c1edb224
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Tue Sep 5 10:01:05 2017 -0400

    Merge pull request #120 from djberg96/gemspec
    
    Bump azure-armrest dependency to 0.8.2
    (cherry picked from commit 91afa868336b337fd2d73bd8de8e44c3b20c4d4f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1488967
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 8154df65c75616bdeda9f13d4972edbeaacbcfaa
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Tue Sep 5 10:01:05 2017 -0400

    Merge pull request #120 from djberg96/gemspec
    
    Bump azure-armrest dependency to 0.8.2
    (cherry picked from commit 91afa868336b337fd2d73bd8de8e44c3b20c4d4f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1488967
```

**Comment by simaishi** [comment]
Backported to `manageiq-providers-azure.gemspec` as well as `manageiq-gems-pending.gemspec` for Fine branch, as `azure-armrest` gem is in 2 places.

**Pull request merged**
